[package]
name = "invincible-reviver"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrock-hematite-nbt = "0.4.2"
chrono = "0.4.40"
iso8601-timestamp = "0.3.3"
miniz_oxide = "0.8.3"
rusty-leveldb = "3.0.2"
zip_archive = "1.2.2"
